# STAGE 1: Build GCC 15.2 on AlmaLinux 9
FROM almalinux:9 AS builder

# Enable CRB for texinfo and install build deps
RUN dnf install -y 'dnf-command(config-manager)' && \
    dnf config-manager --set-enabled crb && \
    dnf install -y wget gcc gcc-c++ zlib-devel glibc-devel make bzip2 \
    perl-devel autoconf automake texinfo diffutils file flex bison

WORKDIR /build
RUN wget https://ftp.gnu.org/gnu/gcc/gcc-15.2.0/gcc-15.2.0.tar.gz && \
    tar -xf gcc-15.2.0.tar.gz

WORKDIR /build/gcc-15.2.0
RUN ./contrib/download_prerequisites

WORKDIR /build/gcc-obj
RUN ../gcc-15.2.0/configure --prefix=/opt/chaintool/gcc15-almalinux \
                --disable-multilib \
                --enable-languages=c,c++ \
                --with-system-zlib \
                --disable-bootstrap \
                --disable-libsanitizer

RUN make -j$(nproc)
RUN make install

# --- REVISED SYSROOT CONSTRUCTION ---
RUN mkdir -p /opt/chaintool/gcc15-almalinux/sysroot/usr/include && \
    mkdir -p /opt/chaintool/gcc15-almalinux/sysroot/usr/lib64 && \
    mkdir -p /opt/chaintool/gcc15-almalinux/sysroot/lib64 && \
    # Link lib64 to usr/lib64 so both paths work
    ln -s usr/lib64 /opt/chaintool/gcc15-almalinux/sysroot/lib64
# Copy Headers
RUN cp -ar /usr/include/* /opt/chaintool/gcc15-almalinux/sysroot/usr/include/
# Copy Runtime Objects
RUN cp -L /usr/lib64/crt*.o /opt/chaintool/gcc15-almalinux/sysroot/usr/lib64/
# Copy the actual shared libraries, avoiding the text-file scripts
# We copy the .so.6 files and then create our own symlinks that the linker will follow
RUN cp -L /lib64/libc.so.6 /opt/chaintool/gcc15-almalinux/sysroot/usr/lib64/ && \
    cp -L /lib64/libm.so.6 /opt/chaintool/gcc15-almalinux/sysroot/usr/lib64/ && \
    cp -L /lib64/libmvec.so.1 /opt/chaintool/gcc15-almalinux/sysroot/usr/lib64/ && \
    cp -L /lib64/ld-linux-x86-64.so.2 /opt/chaintool/gcc15-almalinux/sysroot/usr/lib64/
# Manually create the linker symlinks so -lc and -lm work without using scripts
RUN ln -sf libc.so.6 /opt/chaintool/gcc15-almalinux/sysroot/usr/lib64/libc.so && \
    ln -sf libm.so.6 /opt/chaintool/gcc15-almalinux/sysroot/usr/lib64/libm.so && \
    ln -sf libmvec.so.1 /opt/chaintool/gcc15-almalinux/sysroot/usr/lib64/libmvec.so

################# Ubuntu 24.04 ###################

# STAGE 2: Ubuntu 24.04 Target
FROM ubuntu:24.04

# Copy the toolchain
COPY --from=builder /opt/chaintool/gcc15-almalinux /opt/chaintool/gcc15-almalinux

# Setup path
ENV PATH="/opt/toolchain/gcc15-almalinux/bin:${PATH}"

# Install Ubuntu-side tools to allow the compiler to run and link
RUN apt-get update && apt-get install -y --no-install-recommends \
    binutils \
    make cmake vim \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /root
CMD ["bash"]
